[[main]]
none = "none"

[[main]]
name = "Resume"
pageRef = "resume"
identifier = "tXtV87njAr"
weight = 9999

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "AUxl09Nzci"
weight = 9999

[[footer]]
none = "none"

[[footer]]
name = "Contact"
pageRef = "contact"
identifier = "G47w9hBDST"
weight = 9999
